# Generated by Django 5.2 on 2025-08-11 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('withdrawal_app', '0009_alter_withdrawalinfo_last_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matnr', models.CharField(max_length=40)),
                ('batch', models.CharField(blank=True, max_length=40, null=True)),
                ('pack_qty', models.IntegerField(default=0)),
                ('unit_qty', models.IntegerField(default=0)),
                ('net_val', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_list', to='withdrawal_app.withdrawalinfo')),
            ],
            options={
                'verbose_name': 'Replacement List',
                'verbose_name_plural': 'Replacement List',
                'db_table': 'expr_replacement_list',
            },
        ),
    ]
