# Generated by Django 5.2 on 2025-04-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('mio_id', models.CharField(max_length=40)),
                ('rm_id', models.CharField(max_length=40)),
                ('da_id', models.CharField(max_length=40)),
                ('depot_id', models.CharField(max_length=40)),
                ('route_id', models.CharField(max_length=40)),
                ('partner_id', models.CharField(max_length=40)),
                ('request_approval', models.BooleanField(default=False)),
                ('withdrawal_confirmation', models.BooleanField(default=False)),
                ('replacement_order', models.BooleanField(default=False)),
                ('order_approval', models.BooleanField(default=False)),
                ('order_delivery', models.BooleanField(default=False)),
                ('request_date', models.DateField()),
                ('request_approval_date', models.DateField()),
                ('withdrawal_date', models.DateField()),
                ('withdrawal_approval_date', models.DateField()),
                ('order_date', models.DateField()),
                ('order_approval_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('last_status', models.CharField(choices=[('request', 'Request'), ('withdrawal', 'Withdrawal'), ('delivery', 'Delivery')], default='request', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Withdrawal Info',
                'verbose_name_plural': 'Withdrawal Info',
                'db_table': 'expr_withdrawal_info',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matnr', models.CharField(max_length=40)),
                ('batch', models.CharField(max_length=40)),
                ('pack_qty', models.IntegerField(default=0)),
                ('strip_qty', models.IntegerField(default=0)),
                ('unit_qty', models.IntegerField(default=0)),
                ('net_val', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='withdrawal_app.withdrawalinfo')),
            ],
            options={
                'verbose_name': 'Withdrawal List',
                'verbose_name_plural': 'Withdrawal List',
                'db_table': 'expr_withdrawal_list',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matnr', models.CharField(max_length=40)),
                ('batch', models.CharField(max_length=40)),
                ('pack_qty', models.IntegerField(default=0)),
                ('strip_qty', models.IntegerField(default=0)),
                ('unit_qty', models.IntegerField(default=0)),
                ('net_val', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='withdrawal_app.withdrawalinfo')),
            ],
            options={
                'verbose_name': 'Withdrawal Request List',
                'verbose_name_plural': 'Withdrawal Request List',
                'db_table': 'expr_request_list',
            },
        ),
    ]
