# Generated by Django 5.2 on 2025-05-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalinfo',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalinfo',
            name='order_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalinfo',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalinfo',
            name='request_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalinfo',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalinfo',
            name='withdrawal_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalinfo',
            name='withdrawal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
