# Generated by Django 5.2 on 2025-05-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_app', '0003_alter_withdrawallist_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalinfo',
            name='depot_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
