# Generated by Django 5.2 on 2025-05-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_app', '0004_alter_withdrawalinfo_depot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalinfo',
            name='invoice_type',
            field=models.CharField(choices=[('EXP', 'Expired'), ('GEN', 'General')], default='EXP', max_length=12),
        ),
        migrations.AlterField(
            model_name='withdrawalinfo',
            name='da_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalinfo',
            name='route_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
