# Generated by Django 5.2 on 2025-05-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_app', '0005_withdrawalinfo_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequestlist',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
