# Generated by Django 5.2 on 2025-05-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_app', '0006_withdrawalrequestlist_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawallist',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
