# Generated by Django 5.2 on 2025-08-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withdrawal_app", "0007_withdrawallist_expire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequestlist",
            name="rel_invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequestlist",
            name="rel_invoice_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequestlist",
            name="rel_mio_name",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequestlist",
            name="rel_mio_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="withdrawalinfo",
            name="last_status",
            field=models.CharField(
                choices=[
                    ("request", "Request"),
                    ("request_approved", "Request Approved"),
                    ("withdrawal", "Withdrawal"),
                    ("withdrawal_approved", "Withdrawal Approved"),
                    ("delivery", "Delivery"),
                ],
                default="request",
                max_length=40,
            ),
        ),
    ]
