# Generated by Django 5.2 on 2025-08-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withdrawal_app", "0008_withdrawalrequestlist_rel_invoice_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawalinfo",
            name="last_status",
            field=models.CharField(
                choices=[
                    ("request_pending", "Request Pending"),
                    ("request_approved", "Request Approved"),
                    ("withdrawal_pending", "Withdrawal Pending"),
                    ("withdrawal_approval", "Withdrawal Approval"),
                    ("withdrawal_approved", "Withdrawal Approved"),
                    ("delivery", "Delivery"),
                ],
                default="request_pending",
                max_length=40,
            ),
        ),
    ]
