# Generated by Django 5.2 on 2025-08-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_app', '0009_alter_withdrawalinfo_last_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalinfo',
            name='last_status',
            field=models.CharField(choices=[('request_pending', 'Request Pending'), ('request_approved', 'Request Approved'), ('withdrawal_pending', 'Withdrawal Pending'), ('withdrawal_approval', 'Withdrawal Approval'), ('withdrawal_approved', 'Withdrawal Approved'), ('replacement_approval', 'Replacement Approval'), ('replacement_approved', 'Replacement Approved'), ('delivery_pending', 'Delivery Pending'), ('delivered', 'Delivered')], default='request_pending', max_length=40),
        ),
    ]
