# Generated by Django 5.2 on 2025-08-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withdrawal_app", "0010_alter_withdrawalinfo_last_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalinfo",
            name="delivery_da_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
